### ISSUE TITLE
Shoko Client Beta - Failing to launch

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/ShokoClient#491]
hi,

just did install the beta but im unable to launch the client. Get the following exception:

```
2016-11-12 12:01:40:666] Error|DefaultCtorXamlActivator.CreateInstance => DefaultCtorXamlActivator.CallCtorDelegate => MainWindow..ctor System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.MainWindow..ctor() in D:\My Files\Documents\GitHub\jmmclient\JMMClient\MainWindow.xaml.cs:line 120
[2016-11-12 12:01:40:708] Error|ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.Windows.Markup.XamlParseException: Initialization of 'JMMClient.MainWindow' threw an exception. ---> System.InvalidOperationException: Cannot have nested BeginInit calls on the same instance.
   at System.Windows.FrameworkElement.BeginInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-11-12 12:14:51:562] Error|DefaultCtorXamlActivator.CallCtorDelegate => DefaultCtorXamlActivator.InvokeDelegate => MainWindow..ctor System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.MainWindow..ctor()
[2016-11-12 12:14:51:586] Error|Dispatcher.CatchExceptionStatic => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.Windows.Markup.XamlParseException: Initialization of 'JMMClient.MainWindow' threw an exception. ---> System.InvalidOperationException: Cannot have nested BeginInit calls on the same instance.
   at System.Windows.FrameworkElement.BeginInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-11-12 12:27:15:435] Error|DefaultCtorXamlActivator.CallCtorDelegate => DefaultCtorXamlActivator.InvokeDelegate => MainWindow..ctor System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.MainWindow..ctor()
[2016-11-12 12:27:15:459] Error|Dispatcher.CatchExceptionStatic => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.Windows.Markup.XamlParseException: Initialization of 'JMMClient.MainWindow' threw an exception. ---> System.InvalidOperationException: Cannot have nested BeginInit calls on the same instance.
   at System.Windows.FrameworkElement.BeginInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
````

**Comment by RickDB** [comment]
Fixed in latest beta.
