### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoClient#502]
Updating from old jmm client
shoko find that I used jmmd - and throw at me message about unable to move my files (on current user) and run as admin
running as admin, window about moving my config files is shown
then shoko crash

```
Podpis problemu:
  Nazwa zdarzenia problemu:	CLR20r3
  Podpis problemu: 01:	ShokoDesktop.exe
  Podpis problemu: 02:	3.7.0.216
  Podpis problemu: 03:	585a37a9
  Podpis problemu: 04:	ShokoDesktop
  Podpis problemu: 05:	3.7.0.216
  Podpis problemu: 06:	585a37a9
  Podpis problemu: 07:	918
  Podpis problemu: 08:	6f
  Podpis problemu: 09:	System.NullReferenceException
  Wersja systemu operacyjnego:	6.3.9600.2.0.0.256.4
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	5809
  Dodatkowe informacje 2:	580900b529c7dbbc59a95eaef54aadb0
  Dodatkowe informacje 3:	e187
  Dodatkowe informacje 4:	e187bc03b6bebd205641774fa08ec180
```
Migration wasn't success as I run shoko and there is no settings that I used.

And this is log from first run
```
[2016-12-21 22:35:00:388] Error|App..ctor => AppSettings.LoadSettings => AppSettings.LoadLegacySettingsFromFile Error occured during LoadSettingsManuallyFromFile: Element o tym samym kluczu został już dodany.
[2016-12-21 22:35:08:548] Error|App..ctor => AppSettings.LoadSettings => AppSettings.LoadLegacySettingsFromFile Error occured during LoadSettingsManuallyFromFile: Element o tym samym kluczu został już dodany.
[2016-12-21 22:35:10:424] Info|App.Main => App..ctor => App.UninstallJMMDesktop User cancelled JMM Desktop uninstall
[2016-12-21 22:35:10:453] Error|App.Main => App..ctor => App.CurrentDomain_UnhandledException System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.App..ctor() in C:\projects\jmmclient\JMMClient\App.xaml.cs:line 51
   at JMMClient.App.Main()
[2016-12-21 22:35:12:044] Trace|JMMServerVM.get_Instance => JMMServerVM.Init => JMMServerVM.SetupBinaryClient Unable to connect to JMM Server. Internal exception given: There was no endpoint listening at http://127.0.0.1:8111/JMMServerBinary that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
[2016-12-21 22:38:08:293] Info|App.Main => App..ctor => App.UninstallJMMDesktop User cancelled JMM Desktop uninstall
[2016-12-21 22:38:15:006] Info|App.Main => App..ctor => App.UninstallJMMDesktop User cancelled JMM Desktop uninstall
[2016-12-21 22:38:19:172] Info|App.Main => App..ctor => App.UninstallJMMDesktop JMM Desktop successfully uninstalled
[2016-12-21 22:39:14:550] Trace|JMMServerVM.get_Instance => JMMServerVM.Init => JMMServerVM.SetupBinaryClient Unable to connect to JMM Server. Internal exception given: There was no endpoint listening at http://127.0.0.1:8111/JMMServerBinary that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
[2016-12-21 22:39:16:270] Trace|MainWindow.CheckForUpdatesNew => JMMAutoUpdatesHelper.GetLatestVersionInfo => Utils.DownloadWebPage DownloadWebPage: http://shokoanime.com/files/versions.xml
[2016-12-21 22:39:19:221] Trace|ExecutionContext.RunInternal => Timer.MyTimerCallback => JMMServerVM.SaveServerSettings Error saving server JMM Server Settings. Internal exception given: There was no endpoint listening at http://127.0.0.1:8111/JMMServerBinary that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
[2016-12-21 22:39:21:282] Warn|UTorrentHelperVM.Init => UTorrentHelper.Init => UTorrentHelper.PopulateToken Credentials are not valid for uTorrent
```

and the config file that was created for shoko after/while migrating

```
{"JMMServer_Address":"127.0.0.1","JMMServer_Port":"8111","ImportFolderMappings":"","Culture":"en","ClientSettingsProvider.ServiceUri":"","JMMServerInstance":"ShokoServer","ImagesPath":"C:\\ProgramData\\ShokoDesktop\\images","ShokoServer_Address":"127.0.0.1","ShokoServer_Port":"8111","DashboardWidgetsOrder":"1;2;3;4;5;7;8","DashboardMetroSectionOrder":"2:true;3:true;4:true","MPCWebUIPort":"13579","UTorrentAddress":"","UTorrentPort":"","UTorrentUsername":"","UTorrentPassword":"","TorrentBlackholeFolder":"","BakaBTUsername":"","BakaBTPassword":"","AnimeBytesUsername":"","AnimeBytesPassword":""}
```

**Comment by ElementalCrisis** [comment]
@RickDB can you take a look when you have a moment. Sounds related to my issue with a fresh install and being asked to migrate followed by Desktop crashing. I had to clear everything and run as admin to get passed it.

**Comment by da3dsoul** [comment]
An update to this. I fixed the above error, but it also doesn't set the permissions of ProgramData\Shoko correctly, so it still crashes on normal user

**Comment by RickDB** [comment]
Will take a look, believe we do use the same method as server so wondering if it affects that one as well as they both use safe migrate.

**Comment by da3dsoul** [comment]
It's an issue with the invocation of Utils.GrantAccess. I suggested we make a temp batch file and execute it, as running the command from that works, but not in c# for some reason

**Comment by ElementalCrisis** [comment]
@RickDB, @da3dsoul posted the batch file he made in DevChat if you wanted to check it out.

**Comment by RickDB** [comment]
Added some changes to migration and pretty sure this is sorted, needs re-testing by others :)

**Comment by ElementalCrisis** [comment]
All good on my end, @bigretromike can you give it another go with 3.7.0.1? Also jump on Discord when you have some time, assuming there are no more urgent issues with 3.7, its time to start Nancy.

**Comment by bigretromike** [comment]
Sure, will do 

On December 29, 2016 1:32:03 AM GMT+01:00, ElementalCrisis <notifications@github.com> wrote:
>All good on my end, @bigretromike can you give it another go with
>3.7.0.1? Also jump on Discord when you have some time, assuming there
>are no more urgent issues with 3.7, its time to start Nancy. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/ShokoClient/issues/502#issuecomment-269563593

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
Should be fixed, please confirm when you have a moment and close. :)

**Comment by bigretromike** [comment]
Unable to test it as I installed fresh with 3.7 - which crash on me because I installed it ontop of old shoko, and had to remove dir and install clean. I can close this as you investigated this and probably fixed it with code
